language: perl
perl:
  - "5.18"
  - "5.24"
notifications:
  email: false
env:
  global:
    - "HARNESS_OPTIONS=j9 TEST_MONGO=mongodb://127.0.0.1:27017/mongodbv2"
  matrix:
    - MONGODB=4.0.0
    - MONGODB=4.1.1
matrix:
  fast_finish: true

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --auto
install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version
  - cpan-install --deps       # installs prereqs, including recommends

before_script:
  - mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork

after_script:
  - pkill mongod
